### ISSUE TITLE
Missing CSS - pace-theme-material.css

### ISSUE THREAD

**Issue by temecom** [vectart/ember-cli-pace#25]
After installing on: 
Ember: 
version: 1.13.15
node: 4.2.6
npm: 2.14.10
os: linux x64

Using ENV.pace settings from example. 
pace:{

```
     // addon-specific options to configure theme
     theme: 'material',
     color: 'blue',
```

....

And starting with: 

ember server --proxy http://127.0.0.1:3000 &

I get this: 

Error: Pace theme CSS file was not found: blue/pace-theme-material.css
    at Class.module.exports.treeFor (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli-pace/index.js:80:15)
    at /home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:371:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:369:30)
    at EmberApp.styles (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1105:25)
    at EmberApp.toArray (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1390:10)
    at EmberApp.toTree (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1411:30)
    at module.exports (/home/csmith/Development/dali/dali-analytics-ui/ember-cli-build.js:34:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/lib/models/builder.js:57:19)
    at Class.module.exports.Task.extend.init (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/lib/models/builder.js:91:10)

There appears to be no blue/pace-theme-material.css file in the install package

Changed config to: 

pace:{

```
     // addon-specific options to configure theme
     theme: 'big-counter',
     color: 'blue',
```

and it works.  Sample configuration should be updated. 

Thanks

**Comment by laantorchaweb** [comment]
You're right the material theme is not present on pace.js, there's an open PR for adding it: https://github.com/HubSpot/pace/pull/214

I've updated the docs to fix this issue.
