### ISSUE TITLE
Is it possible to use this package without bower?

### ISSUE THREAD

**Issue by server-may-cry** [vectart/ember-cli-pace#39]
with https://www.npmjs.com/package/pace-progress for example
```
Pace theme CSS file was not found: blue/pace-theme-minimal.css
Error: Pace theme CSS file was not found: blue/pace-theme-minimal.css
    at Class.treeFor (/app/node_modules/ember-cli-pace/index.js:80:15)
    at project.addons.map.addon (/app/node_modules/ember-cli/lib/broccoli/ember-app.js:538:22)
...
```

**Comment by vectart** [comment]
@server-may-cry Are you looking for https://www.npmjs.com/package/ember-cli-pace ?

**Comment by server-may-cry** [comment]
@vectart yep.
I'am currently using [that](https://www.npmjs.com/package/ember-cli-pace) ([this](https://github.com/vectart/ember-cli-pace)) package.
But it require bower
```
$ ember install ember-cli-pace
Yarn: Installed ember-cli-pace
installing pace
  install bower package pace
```

**Comment by t4t5** [comment]
I'm looking for this as well, since the Ember ecosystem in general is moving away from Bower. :)

**Comment by jamesdixon** [comment]
This should be fairly easy to convert to not use bower as long as pace is available somewhere on NPM. I've just converted a bunch of bower-dependent addons to use NPM via [ember-cli-node-assets](https://github.com/dfreeman/ember-cli-node-assets)

**Comment by server-may-cry** [comment]
@jamesdixon can you give an example?

**Comment by jamesdixon** [comment]
@server-may-cry this is something that needs to be directly applied to the addon and not your application. If you'd like to make a PR, check out [ember-cli-node-assets](https://github.com/dfreeman/ember-cli-node-assets) for more info.
